### ISSUE TITLE
posthog.github.io/charts/index.yaml isn't updated

### ISSUE THREAD

**Issue by SuperKruse** [PostHog/charts#10]
It doesn't looks like https://posthog.github.io/charts/index.yaml gets updated.

It is still at version `1.8.0` but it should be at version `1.9.0`

**Comment by mariusandra** [comment]
@fuziontech I think you're the man for the job here. Somehow the chart-releaser action decided to skip releasing 1.3.1: https://github.com/PostHog/charts/runs/811487148 ... not sure why or how.

**Comment by fuziontech** [comment]
Bumped version triggering a new release. Looks like it fixed it. Strange though... Maybe some weird caching issue or eventually consistent issue with github at the time?
https://github.com/PostHog/charts/pull/11

**Comment by SuperKruse** [comment]
There is still a problem. The release tag hasn't been updated in `values.yaml` since version `1.9.0`.
Would a possibility be just to set it to `latest`?

**Comment by mariusandra** [comment]
Hi @SuperKruse , I released a new chart version `1.3.7` with the `1.10.1` docker tag.

Setting it to `latest` [isn't recommended](https://helm.sh/docs/chart_best_practices/pods/#images) by the folks at helm, so it's best to not do that. What we should do instead is to fully automatise the release of these charts. Right now our [release procedure](https://posthog.com/handbook/engineering/release-new-version) is very manual and prone to errors.

Once that's done, these random mistakes won't happen again and there's no need for the latest tag either :).
